### ISSUE TITLE
How was the DTU dataset preprocessed & how do I evaluate DTU ?

### ISSUE THREAD

**Issue by liuyifan22** [maturk/dn-splatter#37]
Hello! Thanks for your great work! 

I am inspired and wanted to try on DTU when I found that the DTU dataset you provided has been preprocessed, and is quite different from other paper's versions. It will be much help to me if you may teach me about the preprocessing code, thanks!

I am also confused about how I can evaluate the results generated. There seems to be no groundtruth meshs or pointclouds 
 in your DTU. Would you please help me out? 

Best wishes!

**Comment by maturk** [comment]
You can download the official DTU dataset, including ground truth point data, from their [website](https://roboimagedata.compute.dtu.dk/?page_id=36). The DTU dataset provided in this repo is processed by the [monosdf](https://github.com/autonomousvision/monosdf) project. We used this for experimentation since it conveniently has normal and monocular depth maps for each frame, as well as SfM points which can be used for monodepth alignment. If you want to extend dn-splatter and use the DTU dataset further, I recommend checking out the evaluation protocol hosted by this [repo](https://github.com/jzhangbs/DTUeval-python) which is widely used in other works for DTU related evaluation. Hope this helps you out.

**Comment by liuyifan22** [comment]
Thanks a lot for your timely and informative reply! With your method, I've successfully evaluated DTU.
And thank you again for your wonderful work!

**Comment by VictorStarkSnow** [comment]
![image](https://github.com/user-attachments/assets/c588d897-30cc-4a87-bae8-32ff092a3e45)
Thank you for your excellent work. I also want to evaluate DTU using the chamfer distance metric, but the mesh I got is quite rough. I would like to ask how the mesh results you got are. Can you share the Chamfer Distance of DTU datasets?

**Comment by xzhoucg** [comment]
Hello!
I would like to ask if the scale of the results I obtained using the command "ns-train dn-platter gsdf -- data./dn2splaster/datasets/DTU/scan65" seems to be inconsistent when using the eval.py in the repo [https://github.com/jzhangbs/DTUeval-python](url) provided by the author?
Would you please help me out? 
The problem is like this:

data_down min: [-1.28036863 -1.695      -1.38417765]
data_down max: [1.655      1.59603447 1.92833484]
BB: [[-176. -218.  542.]
 [ 193.  227.  826.]]
patch: 60

ValueError: Found array with 0 sample(s) (shape=(0, 3)) while a minimum of 1 is required by NearestNeighbors.

Best wishes!
