### ISSUE TITLE
Misplaced Options

### ISSUE THREAD

**Issue by Kairui-SHI** [maturk/dn-splatter#60]
Thanks for your great work! When I try the command [dsine](https://github.com/maturk/dn-splatter?tab=readme-ov-file#2-dsine-normals) in README.md, it shows that I cannot use "--normals-from" and "--normal-format"

![image](https://github.com/user-attachments/assets/303f728b-728e-40d5-94a7-d9acfe1360fb)

**Comment by maturk** [comment]
Hey, can you post the command you are trying to run, I cant see it from the screengrab. Thanks!

**Comment by Kairui-SHI** [comment]
Thanks for your reply! Sure, but I think it's the similar to the readme.

'''bash
ns-train dn-splatter --pipeline.model.use-depth-smooth-loss True --pipeline.model.use-sparse-loss True --pipeline.model.use-binary-opacities True --pipeline.model.use-normal-loss True --pipeline.model.normal-supervision mono  --data tr-rabbit --normals-from pretrained --normal-format opencv
'''

**Comment by maturk** [comment]
Ok, I think I know what the problem is. 

Can you try:

`ns-train dn-splatter --pipeline.model.use-depth-smooth-loss True --pipeline.model.use-sparse-loss True --pipeline.model.use-binary-opacities True --pipeline.model.use-normal-loss True --pipeline.model.normal-supervision mono normal-nerfstudio --data tr-rabbit --normal-format opencv`

Basically remove the `--normals-from` flag and add an extra `normal-nerfstudio` before the data path. 

BTW just a heads up, the readme of this repo is quite outdated and we will do a refactor soon... so some new things and changes will come :) (improvements!)

**Comment by Kairui-SHI** [comment]
Thank you very much, I tried the commend you suggest. It worked. And I think if I want to use pcd, I just need to modify here? [normal_nerfstudio.py#L445](https://github.com/maturk/dn-splatter/blob/aa754d80b72a484f69e769113c065a6e78deb24b/dn_splatter/data/normal_nerfstudio.py#L445)

**Comment by maturk** [comment]
Hi, if your data has been processed by colmap, this should happen automatically. That is, it should load the colmap points automatically for initialization.

If you did not use colmap, then you need to provide a "ply_file_path" in the transforms.json.

**Comment by Kairui-SHI** [comment]
Thanks for your reply! I've already solved load pcd problem. May I ask one more question, how to close depth surprise? My depth is not very accurate(scale).

**Comment by maturk** [comment]
Hi can you further explain what you mean by "depth surprise". What kind of depths do you have, sensor depths or monocular depths?

**Comment by Kairui-SHI** [comment]
Hi, No worry! Thanks for your reply! If I didnt want depth surprise, I can just lower the depth loss weight. Thank you for all of your help!
