### ISSUE TITLE
What versions of torch, gsplat, and nerfstudio should I be using?

### ISSUE THREAD

**Issue by rowellz** [maturk/dn-splatter#79]
I keep running into the Type error issue mentioned in the README that suggests to downgrade to PyTorch 2.0.1. Doing that fixes the problem when running the align_depth.py script, but the downgrade totally breaks nerfstudio. When I try to run `ns-train —help` I get this:

```
    from nerfstudio.utils.external import TCNN_EXISTS, tcnn
  File "/home/user/.local/lib/python3.10/site-packages/nerfstudio/utils/external.py", line 42, in <module>
    import tinycudann
  File "/home/user/.local/lib/python3.10/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/user/.local/lib/python3.10/site-packages/tinycudann/modules.py", line 33, in <module>
    if _C is None:
NameError: name '_C' is not defined
```

**Comment by maturk** [comment]
Hi @rowellz, that is a strange error I have not seen before. The zoe-depth type error is super annoying, and completely avoidable but its a PyTorch side incompatibility afaik. If you are interested in monocular depth generation using Zoe-Depth, my suggestion is to pip install 2.0.1 for just that (just render and make ur depth estimates per frame) and then switch back to a higher pytorch version using a quick pip install. 

The error you are getting with Nerfstudio is probably that since tinycudann was compiled with a different pytorch version, switching to 2.0.1 and not compiling tcnn again, throws the error that the cuda backend is not available.

**Comment by rowellz** [comment]
Ah okay, thanks for that & the quick response! I don’t use pyproject.toml(s) very often, I didn’t realize the versions are in there, will be trying to use `gsplat==1.0.0` Quick follow up question, is it possible to use something besides Zoe-depth? Or perhaps another way to leverage the monocular depth estimation without the alignment step?

**Comment by maturk** [comment]
@rowellz, yes it is possible. Scale/shift alignment is necessary if you are using any of the metric losses like simple MSE, L1, LogL1 etc, but if you use the PearsonDepth loss, then this does not need alignment. 

In fact, I recommend you to use the PearsonDepth loss if you only have monocular depths since based on my experiments it performs the best (but still no where close to what real ToF or lidar sensors can get you). See pic below for on overview:

![image](https://github.com/user-attachments/assets/3146a6c7-87b3-49e8-b9c2-b2ed0c05ef63)

Feel free to use other depth estimation models, like Metric3D or something fancier. Would be cool to support more monodepths in this repo.
