### ISSUE TITLE
UnboundLocalError: local variable 'cam_id_to_camera' referenced before assignment

### ISSUE THREAD

**Issue by justinyeah** [maturk/dn-splatter#94]
![9cb8f76cb46d375ce08f35a89dc9fa9](https://github.com/user-attachments/assets/b2ef2ebd-dc21-4aae-aece-fdf8ac5784c1)

**Comment by maturk** [comment]
Hi, can you paste the structure of your colmap directory here. The structure should be something like:

```
<base_dir>
|---image_path
|   |---<image 0>
|   |---<image 1>
|   |---...
|---colmap
    |---sparse
        |---0
            |---cameras.bin
            |---images.bin
            |---points3D.bin
```

It seems that the script did not find points3d.bin/points3d.txt files in your directory. Carefully check the input path to the script.

**Comment by maturk** [comment]
Also, you can check all the option to the script by running the `--help` command. There is a special flag called `--sparse-path` and the default value is `Path("colmap/sparse/0")`. If your colmap structure is different, e.g. if its "sparse/0" instead of "colmap/sparse/0", you can modify the flag using `--sparse-path sparse/0` command.

**Comment by justinyeah** [comment]
thank u very much ！！! I have made it ! Good luck to you
