### ISSUE TITLE
What's the recommended CUDA version?

### ISSUE THREAD

**Issue by hyqshr** [maturk/dn-splatter#99]
My CUDA version is 11.8 which is the tested version for nerfstudio. I got the error when I run dn-splatter:

<img width="640" alt="image" src="https://github.com/user-attachments/assets/e58143e5-20d6-40a2-9ae0-48151a8796ae" />

**Comment by maturk** [comment]
Ok wow this is a very interesting error. CUDA is not being able to load at __init__.py. Are you certain there is nothing wrong with your cuda installation or torch? Can you test by e.g. installing nerfstudio and trying to use it?

**Comment by maturk** [comment]
An even simpler test is to check if the following works in your python console. In the command line, type the keyword `python` and it will open the interpreter and then you can type the following:
```
import torch
print(torch.cuda.is_available())
```

**Comment by hyqshr** [comment]
@maturk  It returned false. I have multiple conda environment. I create one with torch 2.0.1 with cuda 11.8 to test this repo, my other envs are torch==2.1.2 and they are working with nerfstudio. 
Is there anyway I can make torch==2.1.2 work with this repo? I use torch==2.0.1 because of this error in README:

<img width="495" alt="image" src="https://github.com/user-attachments/assets/2add2c32-a07c-4c9d-bfea-44610e5e4d71" />

**Comment by maturk** [comment]
@hyqshr , feel free to use torch 2.1.2 as well with dn-splatter. It is just that Zoe-Depth has a known incompatibility with this version, so you need to downgrade if you want to use Zoe-Depth prediction in my scripts. 

But I think since `torch.cuda.is_available()` returned false for your 2.1.2 version, something has gone wrong with your installation. You can try make a new environment following the general instructions:

```
# create conda environment
conda create --name dn-splatter -y python=3.10
conda activate dn-splatter
pip install torch==2.1.2+cu118 torchvision==0.16.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit
```

and install nerfstudio/dn-splatter according to the readme instructions.
